# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

julia:
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false
  webhooks: https://coveralls.io/webhook

git:
  depth: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

  allow_failures:
    - julia: nightly
    - arch: arm64

env:
  global:
    - COVERALLS_PARALLEL=true

script:
  - julia --color=yes --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.test("Mill", coverage=true)'
  - julia --color=yes --project=./example -e 'using Pkg; Pkg.instantiate(); cd("example"); include("musk.jl")'

after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
