# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  # - osx

julia:
  - 1.3
  - nightly

notifications:
  email: false
  webhooks: https://coveralls.io/webhook

git:
  depth: false

jobs:
  allow_failures:
    - julia: nightly

coveralls: true

script:
 - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test("Mill", coverage=true)'

env:
  global:
    - COVERALLS_PARALLEL=true

after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
