# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

julia:
  - 1.3
  - nightly

notifications:
  email: false
  webhooks: https://coveralls.io/webhook

git:
  depth: false

jobs:
  allow_failures:
    - julia: nightly
    - arch: arm64

env:
  global:
    - COVERALLS_PARALLEL=true

script:
  - julia --color=yes --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.test("Mill", coverage=true)'
  - julia --color=yes --project=./example -e 'using Pkg; Pkg.instantiate()'
  - julia --color=yes --project=./example example/musk.jl

after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
