# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  # - osx

julia:
  - 1.2
  - 1.3
  - nightly

jobs:
  allow_failures:
    - julia: nightly

## uncomment the following lines to override the default test script
script:
 - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.add(PackageSpec(name="Flux", rev="zygote")); Pkg.instantiate(); Pkg.test()'
